#!/usr/bin/env bash
#installing nginx

sudo apt-get -y update
sudo apt-get -y install nginx
#creation of html page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
