#!/usr/bin/env bash
# script to configure inginx automatically

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

#nginx configuration file
echo "server {
    listen 80;
    listen [::]:80;
    location /redirect_me {
	return 301 http://youtube.com/;
}
}" > /etc/nginx/sites-available/default
service nginx restart
