#!/usr/bin/env bash
# Redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html


ufw allow 'Nginx HTTP'

# Add redirection
new_site="https://youtube.com"
sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" /etc/nginx/sites-available/default

service nginx restart
