#!/usr/bin/env bash
# script to configure inginx automatically

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

#nginx configuration file
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root    /var/www/html;
    index   index.nginx-debian.html;
    location /redirect_me {
	return 301 http://youtube.com/;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
