#!/usr/bin/env bash
#custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

#nginx configuration file
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root    /var/www/html;
    index   index.nginx-debian.html;
    location /redirect_me {
	return 301 http://youtube.com/;
}
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
}
}" > /etc/nginx/sites-available/default
service nginx restart
