#!/usr/bin/env bash
# Installing and configuring HAproxy mylb-01 server

sudo apt-get update
sudo apt-get install -y haproxy
cp -n /etc/haproxy/haproxy.cfg /etc/haproxy/origine

echo "
frontend myfront-end
	bind *:80
	mode http
	default_backend myback-end
backend myback-end
	server nginx1-web-01 54.167.198.176:80 check
	server nginx2-web-02 35.175.102.14:80 check
	balance roundrobin
	mode http
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
