#!/usr/bin/env bash
# Installing and configuring HAproxy mylb-01 server

sudo apt-get update
sudo apt-get install -y haproxy
cp -n /etc/haproxy/haproxy.cfg /etc/haproxy/origine

echo "
frontend myfront-end
	bind *:80
	mode http
	default_backend myback-end
backend myback-end
	server nginx1-web-01 100.26.171.37:80 check
	server nginx2-web-02 54.89.108.245:80 check
	balance roundrobin
	mode http
" > /etc/haproxy/haproxy.cfg

echo "ENABLED=1" > /etc/default/haproxy
sudo service haproxy restart
