#!/usr/bin/env bash
# Installing and configuring HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

echo "
frontend myfront-end
	bind *:80
	mode http
	default_backend myback-end
backend myback-end
	server 484057-web-01 54.209.138.167:80 check
	server 123-web-02 100.26.226.218:80 check
	balance roundrobin
	mode http
" > /etc/haproxy/haproxy.cfg

echo "ENABLED=1" > /etc/default/haproxy
sudo service haproxy restart
