#!/usr/bin/env bash
#displays to infinity and beyond
#with sleep 2 between each iteration
#I am invincible!!! when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
