#!/usr/bin/env bash
#displays best school *10  but for the 9th iteration, displays Best School and then Hi on a new line

count=0
while [ $count -lt 10 ]
do
     if [ $count = 8 ]
     then
	echo "Best School"
	echo "Hi"
     else
	        echo "Best School"
     fi

     ((count++))
done
