#!/usr/bin/env bash
#displays numbers from 1 to 20 and
#bad luck from China for the 4th loop iteration
#bad luck from Italy for the 17th loop iteration

counter=1
while (( counter <= 20))
do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;

	        9)
		        echo $counter
			echo "bad luck from Japan"
			;;


		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac
	((counter++))
done
