#!/usr/bin/env bash
#bash script that displays The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

file=$(ls)
for i in $file
do
	echo "$i"
done
