#!/usr/bin/env bash
# running nginx as nginx and not the root for security reasons

#replaces #user www-data with user nginx in /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
# replaces 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
#changing permissions to read and write for the owner and read for others
chmod 644 /etc/nginx/nginx.conf

sudo -u nginx service nginx start
